# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7b9f315dea1910df1a3d2b2e1cc7cceed39e00ff51a1a65200114819de774285b433dbeb6816634a011ea9462a69bbe42ef90aad9cf4be2348a60d5007ea9223

test:
  secret_key_base: 34ab5b5da815480e5cc4affe63f692519b68326befafd0750f9de1bf462b863aa3d7acda6b0ed0e950083e1c397144027289b2109d057d5987b0c78a21755574

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
